# Generated by Django 5.0 on 2023-12-08 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_file_description_remove_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 44, 4, 581039)),
        ),
        migrations.AlterField(
            model_name='filetransaction',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filetransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 44, 4, 582053)),
        ),
    ]
