# Generated by Django 5.0 on 2023-12-08 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_file_created_at_alter_filetransaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 46, 8, 27325)),
        ),
        migrations.AlterField(
            model_name='filetransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filetransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 46, 8, 28333)),
        ),
    ]
