# Generated by Django 5.0 on 2023-12-08 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_file_created_at_alter_filetransaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 50, 29, 800189)),
        ),
        migrations.AlterField(
            model_name='filetransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
