# Generated by Django 5.0 on 2023-12-08 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_file_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='transaction_type',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='UPLOAD', max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 18, 50, 10, 484488)),
        ),
    ]
