# Generated by Django 5.0 on 2023-12-08 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_file_created_at_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 19, 40, 39, 572283)),
        ),
    ]
